stages:
  - terraform-init
  - terraform-apply
  - terraform-destroy

# Global before_script to install Terraform
before_script:
  - apk add --no-cache curl unzip bash
  - curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
  - unzip terraform.zip
  - mv terraform /usr/local/bin/
  - terraform --version

# Docker
docker_build:
  stage: terraform-init
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $CI_REGISTRY_IMAGE/app:latest .
    - docker push $CI_REGISTRY_IMAGE/app:latest
  only:
    - main

# Cache Terraform plugins and modules
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .terraform/

# Deploy Infrastructure
terraform_apply:
  stage: terraform-apply
  image: alpine
  script:
    - cd terraform/iaas  # or terraform/paas
    - terraform init
    - terraform apply -auto-approve
  only:
    - main

# Destroy Infrastructure
terraform_destroy:
  stage: terraform-destroy
  image: alpine
  script:
    - cd terraform/iaas  # or terraform/paas
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
