---
- name: Automatisation du déploiement Docker et de l'application
  hosts: azure_vm
  become: true
  vars:
    app_path: "/home/azureuser/myapp"
    source_app_path: "{{ ansible_playbook_dir }}/../app/"
  roles:
    - docker_install